/****************************************************************
 * This file is automatically generated.  Do not edit it.
 * version.h updated at Thu Sep 24 13:55:35 EDT 2015 on michurin by jczech
 ****************************************************************/

/* Program version info */
#define MCELL_VERSION "3.3"
#define MCELL_REVISION "4fc664c"
#define MCELL_REVISION_DATE "Thu, 17 Sep 2015 17:16:21 -0400"
#define MCELL_REVISION_COMMITTED 1
#define MCELL_REVISION_BRANCH "master"

/* Build info */
#define MCELL_BUILDDATE  "Thu Sep 24 13:55:35 EDT 2015"
#define MCELL_BUILDUSER  "jczech"
#define MCELL_BUILDHOST  "michurin"
#define MCELL_SRCDIR     "/home/jczech/mcell/source/mcell/src"
#define MCELL_BUILDDIR   "/home/jczech/mcell/source/mcell/build"
#define MCELL_BUILDUNAME "Linux michurin 4.1.4-1-ARCH #1 SMP PREEMPT Mon Aug 3 21:30:37 UTC 2015 x86_64 GNU/Linux"

/* Tool identity and version info */
#define MCELL_FLEX "flex"
#define MCELL_FLEX_PATH "/usr/bin/flex"
#define MCELL_FLEX_VERSION "flex 2.5.39"
#define MCELL_FLEX_FLAGS "-Crema"
#define MCELL_BISON "bison"
#define MCELL_BISON_PATH "/usr/bin/bison"
#define MCELL_BISON_VERSION "bison (GNU Bison) 3.0.4"
#define MCELL_BISON_FLAGS ""
#define MCELL_CC "gcc"
#define MCELL_CC_PATH "/usr/bin/gcc"
#define MCELL_CC_VERSION "gcc (GCC) 5.2.0"
#define MCELL_LD "ld"
#define MCELL_LD_PATH "/usr/bin/ld"
#define MCELL_LD_VERSION "GNU ld (GNU Binutils) 2.25.1"

/* Build options */
#define MCELL_LFLAGS "-Crema"
#define MCELL_YFLAGS ""
#define MCELL_CFLAGS "-g -O2"
#define MCELL_LDFLAGS ""
