/****************************************************************
 * This file is automatically generated.  Do not edit it.
 * version.h updated at Fri Jul 17 15:14:05 PDT 2020 on ntbhusar by ahusar
 ****************************************************************/

/* Program version info */
#define MCELL_VERSION "3.5.1"
#define MCELL_REVISION "ea8bb986"
#define MCELL_REVISION_DATE "Fri, 17 Jul 2020 12:16:38 -0700"
#define MCELL_REVISION_COMMITTED 1
#define MCELL_REVISION_BRANCH "mcell4_bng2"

/* Build info */
#define MCELL_BUILDDATE  "Fri Jul 17 15:14:05 PDT 2020"
#define MCELL_BUILDUSER  "ahusar"
#define MCELL_BUILDHOST  "ntbhusar"
#define MCELL_SRCDIR     "/home/ahusar/src4_ref/mcell/src"
#define MCELL_BUILDDIR   "/home/ahusar/src4_ref/mcell/build/debug"
#define MCELL_BUILDUNAME "Linux ntbhusar 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux"

/* Tool identity and version info */
#define MCELL_FLEX "flex"
#define MCELL_FLEX_PATH "/usr/bin/flex"
#define MCELL_FLEX_VERSION "flex 2.6.1"
#define MCELL_FLEX_FLAGS "-Crema"
#define MCELL_BISON "bison"
#define MCELL_BISON_PATH "/usr/bin/bison"
#define MCELL_BISON_VERSION "bison (GNU Bison) 3.0.4"
#define MCELL_BISON_FLAGS ""
#define MCELL_CC "cc"
#define MCELL_CC_PATH "/usr/bin/cc"
#define MCELL_CC_VERSION "cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516"
#define MCELL_LD "ld"
#define MCELL_LD_PATH "/usr/bin/ld"
#define MCELL_LD_VERSION "GNU ld (GNU Binutils for Debian) 2.28"

/* Build options */
#define MCELL_LFLAGS "-Crema"
#define MCELL_YFLAGS ""
#define MCELL_CFLAGS ""
#define MCELL_LDFLAGS ""
