/****************************************************************
 * This file is automatically generated.  Do not edit it.
 * version.h updated at Thu Sep 29 14:05:19 EDT 2016 on washburne by jacob
 ****************************************************************/

/* Program version info */
#define MCELL_VERSION "3.4"
#define MCELL_REVISION "5ea1fbe"
#define MCELL_REVISION_DATE "Thu, 29 Sep 2016 13:17:41 -0400"
#define MCELL_REVISION_COMMITTED 1
#define MCELL_REVISION_BRANCH "master"

/* Build info */
#define MCELL_BUILDDATE  "Thu Sep 29 14:05:19 EDT 2016"
#define MCELL_BUILDUSER  "jacob"
#define MCELL_BUILDHOST  "washburne"
#define MCELL_SRCDIR     "/home/jacob/mcell/source/mcell/src"
#define MCELL_BUILDDIR   "/home/jacob/mcell/source/mcell/build"
#define MCELL_BUILDUNAME "Linux washburne 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"

/* Tool identity and version info */
#define MCELL_FLEX "flex"
#define MCELL_FLEX_PATH "/usr/bin/flex"
#define MCELL_FLEX_VERSION "flex 2.5.35"
#define MCELL_FLEX_FLAGS "-Crema"
#define MCELL_BISON "bison"
#define MCELL_BISON_PATH "/usr/bin/bison"
#define MCELL_BISON_VERSION "bison (GNU Bison) 3.0.2"
#define MCELL_BISON_FLAGS ""
#define MCELL_CC "clang"
#define MCELL_CC_PATH "/usr/bin/clang"
#define MCELL_CC_VERSION "Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)"
#define MCELL_LD "ld"
#define MCELL_LD_PATH "/usr/bin/ld"
#define MCELL_LD_VERSION "GNU ld (GNU Binutils for Ubuntu) 2.24"

/* Build options */
#define MCELL_LFLAGS "-Crema"
#define MCELL_YFLAGS ""
#define MCELL_CFLAGS "-O3"
#define MCELL_LDFLAGS ""
