/****************************************************************
 * This file is automatically generated.  Do not edit it.
 * version.h updated at Wed Feb 5 12:46:27 PM PST 2025 on huxley by bkaynak
 ****************************************************************/

/* Program version info */
#define MCELL_VERSION "4.1.0"
#define MCELL_REVISION "TBD by hand"
#define MCELL_REVISION_DATE "Mon, 4 Mar 2024 10:18:10 -0800"
#define MCELL_REVISION_COMMITTED 1
#define MCELL_REVISION_BRANCH "mcell4_dev"

/* Build info */
#define MCELL_BUILDDATE  "Wed  Feb 5 12:46:27 PM PST 2025"
#define MCELL_BUILDUSER  "bkaynak"
#define MCELL_BUILDHOST  "huxley"
#define MCELL_SRCDIR     "/home/bkaynak/Desktop/xxx/cpp/mcell/mcell4_builds/mcell4_build_311/mcell/src"
#define MCELL_BUILDDIR   "/nadata/cnl/home/bkaynak/Desktop/xxx/cpp/mcell/mcell4_builds/mcell4_build_311/mcell_tools/work/build_mcell"
#define MCELL_BUILDUNAME "Linux huxley 6.1.0-30-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.124-1 (2025-01-12) x86_64 GNU/Linux"

/* Tool identity and version info */
#define MCELL_FLEX "flex"
#define MCELL_FLEX_PATH "/usr/bin/flex"
#define MCELL_FLEX_VERSION "flex 2.6.4"
#define MCELL_FLEX_FLAGS "-Crema"
#define MCELL_BISON "bison"
#define MCELL_BISON_PATH "/usr/bin/bison"
#define MCELL_BISON_VERSION "bison (GNU Bison) 3.8.2"
#define MCELL_BISON_FLAGS ""
#define MCELL_CC "cc"
#define MCELL_CC_PATH "/usr/bin/cc"
#define MCELL_CC_VERSION "cc (Debian 12.2.0-14) 12.2.0"
#define MCELL_LD "ld"
#define MCELL_LD_PATH "/usr/bin/ld"
#define MCELL_LD_VERSION "GNU ld (GNU Binutils for Ubuntu) 2.40"

/* Build options */
#define MCELL_LFLAGS "-Crema"
#define MCELL_YFLAGS ""
#define MCELL_CFLAGS "-Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unused-variable -Wno-deprecated-declarations -fPIC -D_GNU_SOURCE=1 -O3 -finline-limit=10000 -std=c11 -DPYTHON_VERSION=311 -std=c++17 -fpermissive"
#define MCELL_LDFLAGS ""
