/****************************************************************
 * This file is automatically generated.  Do not edit it.
 * version.h updated at Thu Jun 22 18:15:41 EDT 2017 on oberon by jczech
 ****************************************************************/

/* Program version info */
#define MCELL_VERSION "3.4"
#define MCELL_REVISION "bc89eb1"
#define MCELL_REVISION_DATE "Tue, 20 Jun 2017 15:48:07 -0400"
#define MCELL_REVISION_COMMITTED 1
#define MCELL_REVISION_BRANCH "master"

/* Build info */
#define MCELL_BUILDDATE  "Thu Jun 22 18:15:41 EDT 2017"
#define MCELL_BUILDUSER  "jczech"
#define MCELL_BUILDHOST  "oberon"
#define MCELL_SRCDIR     "/home/jczech/mcell/source/mcell/src"
#define MCELL_BUILDDIR   "/home/jczech/mcell/source/mcell/build"
#define MCELL_BUILDUNAME "Linux oberon 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"

/* Tool identity and version info */
#define MCELL_FLEX "flex"
#define MCELL_FLEX_PATH "/usr/bin/flex"
#define MCELL_FLEX_VERSION "flex 2.6.0"
#define MCELL_FLEX_FLAGS "-Crema"
#define MCELL_BISON "bison"
#define MCELL_BISON_PATH "/usr/bin/bison"
#define MCELL_BISON_VERSION "bison (GNU Bison) 3.0.4"
#define MCELL_BISON_FLAGS ""
#define MCELL_CC "gcc"
#define MCELL_CC_PATH "/usr/bin/gcc"
#define MCELL_CC_VERSION "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609"
#define MCELL_LD "ld"
#define MCELL_LD_PATH "/usr/bin/ld"
#define MCELL_LD_VERSION "GNU ld (GNU Binutils for Ubuntu) 2.26.1"

/* Build options */
#define MCELL_LFLAGS "-Crema"
#define MCELL_YFLAGS ""
#define MCELL_CFLAGS "-g -O2"
#define MCELL_LDFLAGS ""
