# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pymcell3_4')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pymcell3_4')
    _pymcell3_4 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pymcell3_4', [dirname(__file__)])
        except ImportError:
            import _pymcell3_4
            return _pymcell3_4
        if fp is not None:
            try:
                _mod = imp.load_module('_pymcell3_4', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pymcell3_4 = swig_import_helper()
    del swig_import_helper
else:
    import _pymcell3_4
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class World(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, World, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, World, name)
    __repr__ = _swig_repr

    def run_simulation(self, dump_initial_state=False):
        return _pymcell3_4.World_run_simulation(self, dump_initial_state)

    def __init__(self):
        this = _pymcell3_4.new_World()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pymcell3_4.delete_World
    __del__ = lambda self: None
World_swigregister = _pymcell3_4.World_swigregister
World_swigregister(World)

class MCell3WorldConverter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MCell3WorldConverter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MCell3WorldConverter, name)
    __repr__ = _swig_repr

    def convert(self, s):
        return _pymcell3_4.MCell3WorldConverter_convert(self, s)
    __swig_setmethods__["world"] = _pymcell3_4.MCell3WorldConverter_world_set
    __swig_getmethods__["world"] = _pymcell3_4.MCell3WorldConverter_world_get
    if _newclass:
        world = _swig_property(_pymcell3_4.MCell3WorldConverter_world_get, _pymcell3_4.MCell3WorldConverter_world_set)

    def __init__(self):
        this = _pymcell3_4.new_MCell3WorldConverter()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pymcell3_4.delete_MCell3WorldConverter
    __del__ = lambda self: None
MCell3WorldConverter_swigregister = _pymcell3_4.MCell3WorldConverter_swigregister
MCell3WorldConverter_swigregister(MCell3WorldConverter)

# This file is compatible with both classic and new-style classes.


