#! /bin/sh

AUTORECONF=`which autoreconf 2>/dev/null`
if test -x "${AUTORECONF}"; then
  autoreconf -i
else
  echo "Can't find autoreconf.  It may not be installed on this machine."
  echo "Please install autoconf and automake on this machine, or build from"
  echo "the source distribution tarball instead."
fi
