# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mcellSwig', [dirname(__file__)])
        except ImportError:
            import _mcellSwig
            return _mcellSwig
        if fp is not None:
            try:
                _mod = imp.load_module('_mcellSwig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mcellSwig = swig_import_helper()
    del swig_import_helper
else:
    import _mcellSwig
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_mcellSwig.MCELL_SUCCESS_swigconstant(_mcellSwig)
MCELL_SUCCESS = _mcellSwig.MCELL_SUCCESS

_mcellSwig.MCELL_FAIL_swigconstant(_mcellSwig)
MCELL_FAIL = _mcellSwig.MCELL_FAIL
class num_expr_list_head(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, num_expr_list_head, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, num_expr_list_head, name)
    __repr__ = _swig_repr
    __swig_setmethods__["value_head"] = _mcellSwig.num_expr_list_head_value_head_set
    __swig_getmethods__["value_head"] = _mcellSwig.num_expr_list_head_value_head_get
    if _newclass:
        value_head = _swig_property(_mcellSwig.num_expr_list_head_value_head_get, _mcellSwig.num_expr_list_head_value_head_set)
    __swig_setmethods__["value_tail"] = _mcellSwig.num_expr_list_head_value_tail_set
    __swig_getmethods__["value_tail"] = _mcellSwig.num_expr_list_head_value_tail_get
    if _newclass:
        value_tail = _swig_property(_mcellSwig.num_expr_list_head_value_tail_get, _mcellSwig.num_expr_list_head_value_tail_set)
    __swig_setmethods__["value_count"] = _mcellSwig.num_expr_list_head_value_count_set
    __swig_getmethods__["value_count"] = _mcellSwig.num_expr_list_head_value_count_get
    if _newclass:
        value_count = _swig_property(_mcellSwig.num_expr_list_head_value_count_get, _mcellSwig.num_expr_list_head_value_count_set)
    __swig_setmethods__["shared"] = _mcellSwig.num_expr_list_head_shared_set
    __swig_getmethods__["shared"] = _mcellSwig.num_expr_list_head_shared_get
    if _newclass:
        shared = _swig_property(_mcellSwig.num_expr_list_head_shared_get, _mcellSwig.num_expr_list_head_shared_set)

    def __init__(self, *args):
        """__init__(self) -> num_expr_list_head"""
        this = _mcellSwig.new_num_expr_list_head(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_num_expr_list_head
    __del__ = lambda self: None
num_expr_list_head_swigregister = _mcellSwig.num_expr_list_head_swigregister
num_expr_list_head_swigregister(num_expr_list_head)


def mcell_create():
    return _mcellSwig.mcell_create()
mcell_create = _mcellSwig.mcell_create

def mcell_init_state(state):
    return _mcellSwig.mcell_init_state(state)
mcell_init_state = _mcellSwig.mcell_init_state

def mcell_parse_mdl(state):
    return _mcellSwig.mcell_parse_mdl(state)
mcell_parse_mdl = _mcellSwig.mcell_parse_mdl

def mcell_init_simulation(state):
    return _mcellSwig.mcell_init_simulation(state)
mcell_init_simulation = _mcellSwig.mcell_init_simulation

def mcell_init_read_checkpoint(state):
    return _mcellSwig.mcell_init_read_checkpoint(state)
mcell_init_read_checkpoint = _mcellSwig.mcell_init_read_checkpoint

def mcell_init_output(state):
    return _mcellSwig.mcell_init_output(state)
mcell_init_output = _mcellSwig.mcell_init_output

def mcell_set_partition(state, dim, head):
    return _mcellSwig.mcell_set_partition(state, dim, head)
mcell_set_partition = _mcellSwig.mcell_set_partition

def mcell_set_time_step(state, step):
    return _mcellSwig.mcell_set_time_step(state, step)
mcell_set_time_step = _mcellSwig.mcell_set_time_step

def mcell_set_iterations(state, iterations):
    return _mcellSwig.mcell_set_iterations(state, iterations)
mcell_set_iterations = _mcellSwig.mcell_set_iterations

def mcell_print_version():
    return _mcellSwig.mcell_print_version()
mcell_print_version = _mcellSwig.mcell_print_version

def mcell_print_usage(executable_name):
    return _mcellSwig.mcell_print_usage(executable_name)
mcell_print_usage = _mcellSwig.mcell_print_usage

def mcell_print_stats():
    return _mcellSwig.mcell_print_stats()
mcell_print_stats = _mcellSwig.mcell_print_stats

def mcell_argparse(argc, argv, state):
    return _mcellSwig.mcell_argparse(argc, argv, state)
mcell_argparse = _mcellSwig.mcell_argparse

def mcell_copysort_numeric_list(head):
    return _mcellSwig.mcell_copysort_numeric_list(head)
mcell_copysort_numeric_list = _mcellSwig.mcell_copysort_numeric_list

def mcell_sort_numeric_list(head):
    return _mcellSwig.mcell_sort_numeric_list(head)
mcell_sort_numeric_list = _mcellSwig.mcell_sort_numeric_list

def mcell_free_numeric_list(nel):
    return _mcellSwig.mcell_free_numeric_list(nel)
mcell_free_numeric_list = _mcellSwig.mcell_free_numeric_list

def mcell_generate_range(list, start, end, step):
    return _mcellSwig.mcell_generate_range(list, start, end, step)
mcell_generate_range = _mcellSwig.mcell_generate_range

def advance_range(list, tmp_dbl):
    return _mcellSwig.advance_range(list, tmp_dbl)
advance_range = _mcellSwig.advance_range

def mcell_generate_range_singleton(lh, value):
    return _mcellSwig.mcell_generate_range_singleton(lh, value)
mcell_generate_range_singleton = _mcellSwig.mcell_generate_range_singleton

def mcell_print(message):
    return _mcellSwig.mcell_print(message)
mcell_print = _mcellSwig.mcell_print

def is_region_degenerate(reg_ptr):
    return _mcellSwig.is_region_degenerate(reg_ptr)
is_region_degenerate = _mcellSwig.is_region_degenerate

def mcell_create_instance_object(state, name, new_obj):
    return _mcellSwig.mcell_create_instance_object(state, name, new_obj)
mcell_create_instance_object = _mcellSwig.mcell_create_instance_object

def mcell_create_poly_object(state, parent, poly_obj, new_obj):
    return _mcellSwig.mcell_create_poly_object(state, parent, poly_obj, new_obj)
mcell_create_poly_object = _mcellSwig.mcell_create_poly_object

def new_polygon_list(state, obj_ptr, n_vertices, vertices, n_connections, connections):
    return _mcellSwig.new_polygon_list(state, obj_ptr, n_vertices, vertices, n_connections, connections)
new_polygon_list = _mcellSwig.new_polygon_list

def make_new_object(state, obj_name, error_code):
    return _mcellSwig.make_new_object(state, obj_name, error_code)
make_new_object = _mcellSwig.make_new_object

def push_object_name(obj_creation, name):
    return _mcellSwig.push_object_name(obj_creation, name)
push_object_name = _mcellSwig.push_object_name

def pop_object_name(obj_creation):
    return _mcellSwig.pop_object_name(obj_creation)
pop_object_name = _mcellSwig.pop_object_name

def add_child_objects(parent, child_head, child_tail):
    return _mcellSwig.add_child_objects(parent, child_head, child_tail)
add_child_objects = _mcellSwig.add_child_objects

def common_ancestor(a, b):
    return _mcellSwig.common_ancestor(a, b)
common_ancestor = _mcellSwig.common_ancestor

def remove_gaps_from_regions(obj_ptr):
    return _mcellSwig.remove_gaps_from_regions(obj_ptr)
remove_gaps_from_regions = _mcellSwig.remove_gaps_from_regions

def check_degenerate_polygon_list(obj_ptr):
    return _mcellSwig.check_degenerate_polygon_list(obj_ptr)
check_degenerate_polygon_list = _mcellSwig.check_degenerate_polygon_list

def allocate_polygon_object(desc):
    return _mcellSwig.allocate_polygon_object(desc)
allocate_polygon_object = _mcellSwig.allocate_polygon_object

def new_element_list(begin, end):
    return _mcellSwig.new_element_list(begin, end)
new_element_list = _mcellSwig.new_element_list

def free_vertex_list(vert_list):
    return _mcellSwig.free_vertex_list(vert_list)
free_vertex_list = _mcellSwig.free_vertex_list

def free_connection_list(elem_conn_list):
    return _mcellSwig.free_connection_list(elem_conn_list)
free_connection_list = _mcellSwig.free_connection_list

def normalize_elements(reg, existing):
    return _mcellSwig.normalize_elements(reg, existing)
normalize_elements = _mcellSwig.normalize_elements

def count_cuboid_elements(sb):
    return _mcellSwig.count_cuboid_elements(sb)
count_cuboid_elements = _mcellSwig.count_cuboid_elements

def check_patch(b, p1, p2, egd):
    return _mcellSwig.check_patch(b, p1, p2, egd)
check_patch = _mcellSwig.check_patch

def cuboid_patch_to_bits(subd_box, v1, v2, bit_arr):
    return _mcellSwig.cuboid_patch_to_bits(subd_box, v1, v2, bit_arr)
cuboid_patch_to_bits = _mcellSwig.cuboid_patch_to_bits

def mcell_create_region(state, obj_ptr, name):
    return _mcellSwig.mcell_create_region(state, obj_ptr, name)
mcell_create_region = _mcellSwig.mcell_create_region

def make_new_region(state, obj_name, region_last_name):
    return _mcellSwig.make_new_region(state, obj_name, region_last_name)
make_new_region = _mcellSwig.make_new_region

def mcell_add_to_vertex_list(x, y, z, vertices):
    return _mcellSwig.mcell_add_to_vertex_list(x, y, z, vertices)
mcell_add_to_vertex_list = _mcellSwig.mcell_add_to_vertex_list

def mcell_add_to_connection_list(v1, v2, v3, elements):
    return _mcellSwig.mcell_add_to_connection_list(v1, v2, v3, elements)
mcell_add_to_connection_list = _mcellSwig.mcell_add_to_connection_list

def mcell_set_region_elements(rgn, elements, normalize_now):
    return _mcellSwig.mcell_set_region_elements(rgn, elements, normalize_now)
mcell_set_region_elements = _mcellSwig.mcell_set_region_elements

def mcell_add_to_region_list(elements, region_idx):
    return _mcellSwig.mcell_add_to_region_list(elements, region_idx)
mcell_add_to_region_list = _mcellSwig.mcell_add_to_region_list
class output_column_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, output_column_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, output_column_list, name)
    __repr__ = _swig_repr
    __swig_setmethods__["column_head"] = _mcellSwig.output_column_list_column_head_set
    __swig_getmethods__["column_head"] = _mcellSwig.output_column_list_column_head_get
    if _newclass:
        column_head = _swig_property(_mcellSwig.output_column_list_column_head_get, _mcellSwig.output_column_list_column_head_set)
    __swig_setmethods__["column_tail"] = _mcellSwig.output_column_list_column_tail_set
    __swig_getmethods__["column_tail"] = _mcellSwig.output_column_list_column_tail_get
    if _newclass:
        column_tail = _swig_property(_mcellSwig.output_column_list_column_tail_get, _mcellSwig.output_column_list_column_tail_set)

    def __init__(self, *args):
        """__init__(self) -> output_column_list"""
        this = _mcellSwig.new_output_column_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_output_column_list
    __del__ = lambda self: None
output_column_list_swigregister = _mcellSwig.output_column_list_swigregister
output_column_list_swigregister(output_column_list)

class output_set_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, output_set_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, output_set_list, name)
    __repr__ = _swig_repr
    __swig_setmethods__["set_head"] = _mcellSwig.output_set_list_set_head_set
    __swig_getmethods__["set_head"] = _mcellSwig.output_set_list_set_head_get
    if _newclass:
        set_head = _swig_property(_mcellSwig.output_set_list_set_head_get, _mcellSwig.output_set_list_set_head_set)
    __swig_setmethods__["set_tail"] = _mcellSwig.output_set_list_set_tail_set
    __swig_getmethods__["set_tail"] = _mcellSwig.output_set_list_set_tail_get
    if _newclass:
        set_tail = _swig_property(_mcellSwig.output_set_list_set_tail_get, _mcellSwig.output_set_list_set_tail_set)

    def __init__(self, *args):
        """__init__(self) -> output_set_list"""
        this = _mcellSwig.new_output_set_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_output_set_list
    __del__ = lambda self: None
output_set_list_swigregister = _mcellSwig.output_set_list_swigregister
output_set_list_swigregister(output_set_list)

class output_times_inlist(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, output_times_inlist, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, output_times_inlist, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _mcellSwig.output_times_inlist_type_set
    __swig_getmethods__["type"] = _mcellSwig.output_times_inlist_type_get
    if _newclass:
        type = _swig_property(_mcellSwig.output_times_inlist_type_get, _mcellSwig.output_times_inlist_type_set)
    __swig_setmethods__["step"] = _mcellSwig.output_times_inlist_step_set
    __swig_getmethods__["step"] = _mcellSwig.output_times_inlist_step_get
    if _newclass:
        step = _swig_property(_mcellSwig.output_times_inlist_step_get, _mcellSwig.output_times_inlist_step_set)
    __swig_setmethods__["values"] = _mcellSwig.output_times_inlist_values_set
    __swig_getmethods__["values"] = _mcellSwig.output_times_inlist_values_get
    if _newclass:
        values = _swig_property(_mcellSwig.output_times_inlist_values_get, _mcellSwig.output_times_inlist_values_set)

    def __init__(self, *args):
        """__init__(self) -> output_times_inlist"""
        this = _mcellSwig.new_output_times_inlist(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_output_times_inlist
    __del__ = lambda self: None
output_times_inlist_swigregister = _mcellSwig.output_times_inlist_swigregister
output_times_inlist_swigregister(output_times_inlist)


def mcell_get_count(nameM, nameR, world):
    return _mcellSwig.mcell_get_count(nameM, nameR, world)
mcell_get_count = _mcellSwig.mcell_get_count

def mcell_new_output_request(state, target, orientation, location, img, report_flags):
    return _mcellSwig.mcell_new_output_request(state, target, orientation, location, img, report_flags)
mcell_new_output_request = _mcellSwig.mcell_new_output_request

def mcell_create_new_output_set(comment, exact_time, col_head, file_flags, outfile_name):
    return _mcellSwig.mcell_create_new_output_set(comment, exact_time, col_head, file_flags, outfile_name)
mcell_create_new_output_set = _mcellSwig.mcell_create_new_output_set

def mcell_add_reaction_output_block(state, osets, buffer_size, otimes):
    return _mcellSwig.mcell_add_reaction_output_block(state, osets, buffer_size, otimes)
mcell_add_reaction_output_block = _mcellSwig.mcell_add_reaction_output_block

def mcell_create_count(state, target, orientation, location, report_flags, custom_header, count_list):
    return _mcellSwig.mcell_create_count(state, target, orientation, location, report_flags, custom_header, count_list)
mcell_create_count = _mcellSwig.mcell_create_count

_mcellSwig.REGULAR_ARROW_swigconstant(_mcellSwig)
REGULAR_ARROW = _mcellSwig.REGULAR_ARROW

_mcellSwig.ARROW_BIDIRECTIONAL_swigconstant(_mcellSwig)
ARROW_BIDIRECTIONAL = _mcellSwig.ARROW_BIDIRECTIONAL

_mcellSwig.ARROW_CATALYTIC_swigconstant(_mcellSwig)
ARROW_CATALYTIC = _mcellSwig.ARROW_CATALYTIC

_mcellSwig.RATE_UNSET_swigconstant(_mcellSwig)
RATE_UNSET = _mcellSwig.RATE_UNSET

_mcellSwig.RATE_CONSTANT_swigconstant(_mcellSwig)
RATE_CONSTANT = _mcellSwig.RATE_CONSTANT

_mcellSwig.RATE_FILE_swigconstant(_mcellSwig)
RATE_FILE = _mcellSwig.RATE_FILE

_mcellSwig.RFLCT_swigconstant(_mcellSwig)
RFLCT = _mcellSwig.RFLCT

_mcellSwig.TRANSP_swigconstant(_mcellSwig)
TRANSP = _mcellSwig.TRANSP

_mcellSwig.SINK_swigconstant(_mcellSwig)
SINK = _mcellSwig.SINK
class reaction_def(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, reaction_def, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, reaction_def, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sym"] = _mcellSwig.reaction_def_sym_set
    __swig_getmethods__["sym"] = _mcellSwig.reaction_def_sym_get
    if _newclass:
        sym = _swig_property(_mcellSwig.reaction_def_sym_get, _mcellSwig.reaction_def_sym_set)

    def __init__(self, *args):
        """__init__(self) -> reaction_def"""
        this = _mcellSwig.new_reaction_def(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_reaction_def
    __del__ = lambda self: None
reaction_def_swigregister = _mcellSwig.reaction_def_swigregister
reaction_def_swigregister(reaction_def)

class release_single_molecule_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, release_single_molecule_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, release_single_molecule_list, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rsm_head"] = _mcellSwig.release_single_molecule_list_rsm_head_set
    __swig_getmethods__["rsm_head"] = _mcellSwig.release_single_molecule_list_rsm_head_get
    if _newclass:
        rsm_head = _swig_property(_mcellSwig.release_single_molecule_list_rsm_head_get, _mcellSwig.release_single_molecule_list_rsm_head_set)
    __swig_setmethods__["rsm_tail"] = _mcellSwig.release_single_molecule_list_rsm_tail_set
    __swig_getmethods__["rsm_tail"] = _mcellSwig.release_single_molecule_list_rsm_tail_get
    if _newclass:
        rsm_tail = _swig_property(_mcellSwig.release_single_molecule_list_rsm_tail_get, _mcellSwig.release_single_molecule_list_rsm_tail_set)
    __swig_setmethods__["rsm_count"] = _mcellSwig.release_single_molecule_list_rsm_count_set
    __swig_getmethods__["rsm_count"] = _mcellSwig.release_single_molecule_list_rsm_count_get
    if _newclass:
        rsm_count = _swig_property(_mcellSwig.release_single_molecule_list_rsm_count_get, _mcellSwig.release_single_molecule_list_rsm_count_set)

    def __init__(self, *args):
        """__init__(self) -> release_single_molecule_list"""
        this = _mcellSwig.new_release_single_molecule_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_release_single_molecule_list
    __del__ = lambda self: None
release_single_molecule_list_swigregister = _mcellSwig.release_single_molecule_list_swigregister
release_single_molecule_list_swigregister(release_single_molecule_list)

class reaction_arrow(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, reaction_arrow, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, reaction_arrow, name)
    __repr__ = _swig_repr
    __swig_setmethods__["flags"] = _mcellSwig.reaction_arrow_flags_set
    __swig_getmethods__["flags"] = _mcellSwig.reaction_arrow_flags_get
    if _newclass:
        flags = _swig_property(_mcellSwig.reaction_arrow_flags_get, _mcellSwig.reaction_arrow_flags_set)
    __swig_setmethods__["catalyst"] = _mcellSwig.reaction_arrow_catalyst_set
    __swig_getmethods__["catalyst"] = _mcellSwig.reaction_arrow_catalyst_get
    if _newclass:
        catalyst = _swig_property(_mcellSwig.reaction_arrow_catalyst_get, _mcellSwig.reaction_arrow_catalyst_set)

    def __init__(self, *args):
        """__init__(self) -> reaction_arrow"""
        this = _mcellSwig.new_reaction_arrow(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_reaction_arrow
    __del__ = lambda self: None
reaction_arrow_swigregister = _mcellSwig.reaction_arrow_swigregister
reaction_arrow_swigregister(reaction_arrow)

class reaction_rate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, reaction_rate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, reaction_rate, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rate_type"] = _mcellSwig.reaction_rate_rate_type_set
    __swig_getmethods__["rate_type"] = _mcellSwig.reaction_rate_rate_type_get
    if _newclass:
        rate_type = _swig_property(_mcellSwig.reaction_rate_rate_type_get, _mcellSwig.reaction_rate_rate_type_set)
    __swig_getmethods__["v"] = _mcellSwig.reaction_rate_v_get
    if _newclass:
        v = _swig_property(_mcellSwig.reaction_rate_v_get)

    def __init__(self, *args):
        """__init__(self) -> reaction_rate"""
        this = _mcellSwig.new_reaction_rate(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_reaction_rate
    __del__ = lambda self: None
reaction_rate_swigregister = _mcellSwig.reaction_rate_swigregister
reaction_rate_swigregister(reaction_rate)

class reaction_rate_v(_object):
    """Proxy of C reaction_rate_v struct."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, reaction_rate_v, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, reaction_rate_v, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rate_constant"] = _mcellSwig.reaction_rate_v_rate_constant_set
    __swig_getmethods__["rate_constant"] = _mcellSwig.reaction_rate_v_rate_constant_get
    if _newclass:
        rate_constant = _swig_property(_mcellSwig.reaction_rate_v_rate_constant_get, _mcellSwig.reaction_rate_v_rate_constant_set)
    __swig_setmethods__["rate_file"] = _mcellSwig.reaction_rate_v_rate_file_set
    __swig_getmethods__["rate_file"] = _mcellSwig.reaction_rate_v_rate_file_get
    if _newclass:
        rate_file = _swig_property(_mcellSwig.reaction_rate_v_rate_file_get, _mcellSwig.reaction_rate_v_rate_file_set)

    def __init__(self, *args):
        """__init__(self) -> reaction_rate_v"""
        this = _mcellSwig.new_reaction_rate_v(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_reaction_rate_v
    __del__ = lambda self: None
reaction_rate_v_swigregister = _mcellSwig.reaction_rate_v_swigregister
reaction_rate_v_swigregister(reaction_rate_v)

class reaction_rates(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, reaction_rates, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, reaction_rates, name)
    __repr__ = _swig_repr
    __swig_setmethods__["forward_rate"] = _mcellSwig.reaction_rates_forward_rate_set
    __swig_getmethods__["forward_rate"] = _mcellSwig.reaction_rates_forward_rate_get
    if _newclass:
        forward_rate = _swig_property(_mcellSwig.reaction_rates_forward_rate_get, _mcellSwig.reaction_rates_forward_rate_set)
    __swig_setmethods__["backward_rate"] = _mcellSwig.reaction_rates_backward_rate_set
    __swig_getmethods__["backward_rate"] = _mcellSwig.reaction_rates_backward_rate_get
    if _newclass:
        backward_rate = _swig_property(_mcellSwig.reaction_rates_backward_rate_get, _mcellSwig.reaction_rates_backward_rate_set)

    def __init__(self, *args):
        """__init__(self) -> reaction_rates"""
        this = _mcellSwig.new_reaction_rates(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_reaction_rates
    __del__ = lambda self: None
reaction_rates_swigregister = _mcellSwig.reaction_rates_swigregister
reaction_rates_swigregister(reaction_rates)


def mcell_modify_rate_constant(world, name, rate):
    return _mcellSwig.mcell_modify_rate_constant(world, name, rate)
mcell_modify_rate_constant = _mcellSwig.mcell_modify_rate_constant

def mcell_add_reaction(notify, r_step_release, rxn_sym_table, radial_subdivisions, vacancy_search_dist2, reactants, react_arrow, surf_class, products, pathname, rates, forward_rate_filename, backward_rate_filename):
    return _mcellSwig.mcell_add_reaction(notify, r_step_release, rxn_sym_table, radial_subdivisions, vacancy_search_dist2, reactants, react_arrow, surf_class, products, pathname, rates, forward_rate_filename, backward_rate_filename)
mcell_add_reaction = _mcellSwig.mcell_add_reaction

def mcell_add_surface_reaction(rxn_sym_table, reaction_type, surface_class, reactant_sym, orient):
    return _mcellSwig.mcell_add_surface_reaction(rxn_sym_table, reaction_type, surface_class, reactant_sym, orient)
mcell_add_surface_reaction = _mcellSwig.mcell_add_surface_reaction

def mcell_add_concentration_clamp(rxn_sym_table, surface_class, mol_sym, orient, conc):
    return _mcellSwig.mcell_add_concentration_clamp(rxn_sym_table, surface_class, mol_sym, orient, conc)
mcell_add_concentration_clamp = _mcellSwig.mcell_add_concentration_clamp

def init_reactions(state):
    return _mcellSwig.init_reactions(state)
init_reactions = _mcellSwig.init_reactions

def mcell_change_reaction_rate(state, reaction_name, new_rate):
    return _mcellSwig.mcell_change_reaction_rate(state, reaction_name, new_rate)
mcell_change_reaction_rate = _mcellSwig.mcell_change_reaction_rate

def mcell_create_reaction_rates(forwardRateType, forwardRate, backwardRateType, backwardRate):
    return _mcellSwig.mcell_create_reaction_rates(forwardRateType, forwardRate, backwardRateType, backwardRate)
mcell_create_reaction_rates = _mcellSwig.mcell_create_reaction_rates

def mcell_create_geometrical_release_site(state, parent, site_name, shape, position, diameter, mol, num_molecules, release_prob, pattern_name, new_object):
    return _mcellSwig.mcell_create_geometrical_release_site(state, parent, site_name, shape, position, diameter, mol, num_molecules, release_prob, pattern_name, new_object)
mcell_create_geometrical_release_site = _mcellSwig.mcell_create_geometrical_release_site

def mcell_start_release_site(state, sym_ptr, obj):
    return _mcellSwig.mcell_start_release_site(state, sym_ptr, obj)
mcell_start_release_site = _mcellSwig.mcell_start_release_site

def mcell_finish_release_site(sym_ptr, obj):
    return _mcellSwig.mcell_finish_release_site(sym_ptr, obj)
mcell_finish_release_site = _mcellSwig.mcell_finish_release_site

def set_release_site_concentration(rel_site_obj_ptr, conc):
    return _mcellSwig.set_release_site_concentration(rel_site_obj_ptr, conc)
set_release_site_concentration = _mcellSwig.set_release_site_concentration

def mcell_create_region_release(state, parent, release_on_in, site_name, reg_name, mol, num_molecules, rel_prob, pattern_name, new_object):
    return _mcellSwig.mcell_create_region_release(state, parent, release_on_in, site_name, reg_name, mol, num_molecules, rel_prob, pattern_name, new_object)
mcell_create_region_release = _mcellSwig.mcell_create_region_release

def mcell_set_release_site_geometry_region(state, rel_site_obj_ptr, objp, re):
    return _mcellSwig.mcell_set_release_site_geometry_region(state, rel_site_obj_ptr, objp, re)
mcell_set_release_site_geometry_region = _mcellSwig.mcell_set_release_site_geometry_region

def check_release_regions(rel, parent, instance):
    return _mcellSwig.check_release_regions(rel, parent, instance)
check_release_regions = _mcellSwig.check_release_regions

def is_release_site_valid(rel_site_obj_ptr):
    return _mcellSwig.is_release_site_valid(rel_site_obj_ptr)
is_release_site_valid = _mcellSwig.is_release_site_valid

def new_release_region_expr_term(my_sym):
    return _mcellSwig.new_release_region_expr_term(my_sym)
new_release_region_expr_term = _mcellSwig.new_release_region_expr_term

def set_release_site_constant_number(rel_site_obj_ptr, num):
    return _mcellSwig.set_release_site_constant_number(rel_site_obj_ptr, num)
set_release_site_constant_number = _mcellSwig.set_release_site_constant_number

def set_release_site_gaussian_number(rel_site_obj_ptr, mean, stdev):
    return _mcellSwig.set_release_site_gaussian_number(rel_site_obj_ptr, mean, stdev)
set_release_site_gaussian_number = _mcellSwig.set_release_site_gaussian_number

def new_release_region_expr_binary(reL, reR, op):
    return _mcellSwig.new_release_region_expr_binary(reL, reR, op)
new_release_region_expr_binary = _mcellSwig.new_release_region_expr_binary

def set_release_site_location(state, rel_site_obj_ptr, location):
    return _mcellSwig.set_release_site_location(state, rel_site_obj_ptr, location)
set_release_site_location = _mcellSwig.set_release_site_location
class mcell_species_spec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mcell_species_spec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mcell_species_spec, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _mcellSwig.mcell_species_spec_name_set
    __swig_getmethods__["name"] = _mcellSwig.mcell_species_spec_name_get
    if _newclass:
        name = _swig_property(_mcellSwig.mcell_species_spec_name_get, _mcellSwig.mcell_species_spec_name_set)
    __swig_setmethods__["D"] = _mcellSwig.mcell_species_spec_D_set
    __swig_getmethods__["D"] = _mcellSwig.mcell_species_spec_D_get
    if _newclass:
        D = _swig_property(_mcellSwig.mcell_species_spec_D_get, _mcellSwig.mcell_species_spec_D_set)
    __swig_setmethods__["is_2d"] = _mcellSwig.mcell_species_spec_is_2d_set
    __swig_getmethods__["is_2d"] = _mcellSwig.mcell_species_spec_is_2d_get
    if _newclass:
        is_2d = _swig_property(_mcellSwig.mcell_species_spec_is_2d_get, _mcellSwig.mcell_species_spec_is_2d_set)
    __swig_setmethods__["custom_time_step"] = _mcellSwig.mcell_species_spec_custom_time_step_set
    __swig_getmethods__["custom_time_step"] = _mcellSwig.mcell_species_spec_custom_time_step_get
    if _newclass:
        custom_time_step = _swig_property(_mcellSwig.mcell_species_spec_custom_time_step_get, _mcellSwig.mcell_species_spec_custom_time_step_set)
    __swig_setmethods__["target_only"] = _mcellSwig.mcell_species_spec_target_only_set
    __swig_getmethods__["target_only"] = _mcellSwig.mcell_species_spec_target_only_get
    if _newclass:
        target_only = _swig_property(_mcellSwig.mcell_species_spec_target_only_get, _mcellSwig.mcell_species_spec_target_only_set)
    __swig_setmethods__["max_step_length"] = _mcellSwig.mcell_species_spec_max_step_length_set
    __swig_getmethods__["max_step_length"] = _mcellSwig.mcell_species_spec_max_step_length_get
    if _newclass:
        max_step_length = _swig_property(_mcellSwig.mcell_species_spec_max_step_length_get, _mcellSwig.mcell_species_spec_max_step_length_set)
    __swig_setmethods__["space_step"] = _mcellSwig.mcell_species_spec_space_step_set
    __swig_getmethods__["space_step"] = _mcellSwig.mcell_species_spec_space_step_get
    if _newclass:
        space_step = _swig_property(_mcellSwig.mcell_species_spec_space_step_get, _mcellSwig.mcell_species_spec_space_step_set)

    def __init__(self, *args):
        """__init__(self) -> mcell_species_spec"""
        this = _mcellSwig.new_mcell_species_spec(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_mcell_species_spec
    __del__ = lambda self: None
mcell_species_spec_swigregister = _mcellSwig.mcell_species_spec_swigregister
mcell_species_spec_swigregister(mcell_species_spec)

class mcell_species(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mcell_species, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mcell_species, name)
    __repr__ = _swig_repr
    __swig_setmethods__["next"] = _mcellSwig.mcell_species_next_set
    __swig_getmethods__["next"] = _mcellSwig.mcell_species_next_get
    if _newclass:
        next = _swig_property(_mcellSwig.mcell_species_next_get, _mcellSwig.mcell_species_next_set)
    __swig_setmethods__["mol_type"] = _mcellSwig.mcell_species_mol_type_set
    __swig_getmethods__["mol_type"] = _mcellSwig.mcell_species_mol_type_get
    if _newclass:
        mol_type = _swig_property(_mcellSwig.mcell_species_mol_type_get, _mcellSwig.mcell_species_mol_type_set)
    __swig_setmethods__["orient_set"] = _mcellSwig.mcell_species_orient_set_set
    __swig_getmethods__["orient_set"] = _mcellSwig.mcell_species_orient_set_get
    if _newclass:
        orient_set = _swig_property(_mcellSwig.mcell_species_orient_set_get, _mcellSwig.mcell_species_orient_set_set)
    __swig_setmethods__["orient"] = _mcellSwig.mcell_species_orient_set
    __swig_getmethods__["orient"] = _mcellSwig.mcell_species_orient_get
    if _newclass:
        orient = _swig_property(_mcellSwig.mcell_species_orient_get, _mcellSwig.mcell_species_orient_set)

    def __init__(self, *args):
        """__init__(self) -> mcell_species"""
        this = _mcellSwig.new_mcell_species(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_mcell_species
    __del__ = lambda self: None
mcell_species_swigregister = _mcellSwig.mcell_species_swigregister
mcell_species_swigregister(mcell_species)

class mcell_species_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mcell_species_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mcell_species_list, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mol_type_head"] = _mcellSwig.mcell_species_list_mol_type_head_set
    __swig_getmethods__["mol_type_head"] = _mcellSwig.mcell_species_list_mol_type_head_get
    if _newclass:
        mol_type_head = _swig_property(_mcellSwig.mcell_species_list_mol_type_head_get, _mcellSwig.mcell_species_list_mol_type_head_set)
    __swig_setmethods__["mol_type_tail"] = _mcellSwig.mcell_species_list_mol_type_tail_set
    __swig_getmethods__["mol_type_tail"] = _mcellSwig.mcell_species_list_mol_type_tail_get
    if _newclass:
        mol_type_tail = _swig_property(_mcellSwig.mcell_species_list_mol_type_tail_get, _mcellSwig.mcell_species_list_mol_type_tail_set)

    def __init__(self, *args):
        """__init__(self) -> mcell_species_list"""
        this = _mcellSwig.new_mcell_species_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mcellSwig.delete_mcell_species_list
    __del__ = lambda self: None
mcell_species_list_swigregister = _mcellSwig.mcell_species_list_swigregister
mcell_species_list_swigregister(mcell_species_list)


def mcell_create_species(state, species, species_ptr):
    return _mcellSwig.mcell_create_species(state, species, species_ptr)
mcell_create_species = _mcellSwig.mcell_create_species

def mcell_add_to_species_list(species_ptr, is_oriented, orientation, species_list):
    return _mcellSwig.mcell_add_to_species_list(species_ptr, is_oriented, orientation, species_list)
mcell_add_to_species_list = _mcellSwig.mcell_add_to_species_list

def mcell_delete_species_list(species):
    return _mcellSwig.mcell_delete_species_list(species)
mcell_delete_species_list = _mcellSwig.mcell_delete_species_list

def new_mol_species(state, name, sym_ptr):
    return _mcellSwig.new_mol_species(state, name, sym_ptr)
new_mol_species = _mcellSwig.new_mol_species

def mcell_add_surf_class_properties(state, reaction_type, sc_sym, reactant_sym, orient):
    return _mcellSwig.mcell_add_surf_class_properties(state, reaction_type, sc_sym, reactant_sym, orient)
mcell_add_surf_class_properties = _mcellSwig.mcell_add_surf_class_properties

def mcell_create_surf_class(state, surf_class_name, sc_sym):
    return _mcellSwig.mcell_create_surf_class(state, surf_class_name, sc_sym)
mcell_create_surf_class = _mcellSwig.mcell_create_surf_class

def mcell_add_mol_release_to_surf_class(state, sc_sym, sm_info, quantity, density_or_num, smd_list):
    return _mcellSwig.mcell_add_mol_release_to_surf_class(state, sc_sym, sm_info, quantity, density_or_num, smd_list)
mcell_add_mol_release_to_surf_class = _mcellSwig.mcell_add_mol_release_to_surf_class

def mcell_assign_surf_class_to_region(sc_sym, rgn):
    return _mcellSwig.mcell_assign_surf_class_to_region(sc_sym, rgn)
mcell_assign_surf_class_to_region = _mcellSwig.mcell_assign_surf_class_to_region

def install_emergency_output_hooks(world):
    return _mcellSwig.install_emergency_output_hooks(world)
install_emergency_output_hooks = _mcellSwig.install_emergency_output_hooks

def truncate_output_file(name, start_value):
    return _mcellSwig.truncate_output_file(name, start_value)
truncate_output_file = _mcellSwig.truncate_output_file

def add_trigger_output(world, c, ear, n, flags):
    return _mcellSwig.add_trigger_output(world, c, ear, n, flags)
add_trigger_output = _mcellSwig.add_trigger_output

def flush_reaction_output(world):
    return _mcellSwig.flush_reaction_output(world)
flush_reaction_output = _mcellSwig.flush_reaction_output

def check_reaction_output_file(os):
    return _mcellSwig.check_reaction_output_file(os)
check_reaction_output_file = _mcellSwig.check_reaction_output_file

def update_reaction_output(world, block):
    return _mcellSwig.update_reaction_output(world, block)
update_reaction_output = _mcellSwig.update_reaction_output

def write_reaction_output(world, set):
    return _mcellSwig.write_reaction_output(world, set)
write_reaction_output = _mcellSwig.write_reaction_output

def new_output_expr(oexpr_mem):
    return _mcellSwig.new_output_expr(oexpr_mem)
new_output_expr = _mcellSwig.new_output_expr

def set_oexpr_column(oe, oc):
    return _mcellSwig.set_oexpr_column(oe, oc)
set_oexpr_column = _mcellSwig.set_oexpr_column

def learn_oexpr_flags(oe):
    return _mcellSwig.learn_oexpr_flags(oe)
learn_oexpr_flags = _mcellSwig.learn_oexpr_flags

def dupl_oexpr_tree(root, oexpr_mem):
    return _mcellSwig.dupl_oexpr_tree(root, oexpr_mem)
dupl_oexpr_tree = _mcellSwig.dupl_oexpr_tree

def first_oexpr_tree(root):
    return _mcellSwig.first_oexpr_tree(root)
first_oexpr_tree = _mcellSwig.first_oexpr_tree

def next_oexpr_tree(leaf):
    return _mcellSwig.next_oexpr_tree(leaf)
next_oexpr_tree = _mcellSwig.next_oexpr_tree

def eval_oexpr_tree(root, skip_const):
    return _mcellSwig.eval_oexpr_tree(root, skip_const)
eval_oexpr_tree = _mcellSwig.eval_oexpr_tree

def oexpr_flood_convert(root, old_oper, new_oper):
    return _mcellSwig.oexpr_flood_convert(root, old_oper, new_oper)
oexpr_flood_convert = _mcellSwig.oexpr_flood_convert

def oexpr_title(root):
    return _mcellSwig.oexpr_title(root)
oexpr_title = _mcellSwig.oexpr_title

def my_strcat(s1, s2):
    return _mcellSwig.my_strcat(s1, s2)
my_strcat = _mcellSwig.my_strcat

def strip_quotes(s):
    return _mcellSwig.strip_quotes(s)
strip_quotes = _mcellSwig.strip_quotes
# This file is compatible with both classic and new-style classes.

cvar = _mcellSwig.cvar

