# ============================================================
# This is the Windows (PowerShell) equivalent of version.sh.
# It generates a version.h C header file.
# Usage:  powershell -ExecutionPolicy Bypass -File version.ps1 -OutputFile version.h
#   or:   powershell -ExecutionPolicy Bypass -File version.ps1 > version.h
# Build flags can be passed via parameters or environment variables.
# ============================================================

param(
    [string]$OutputFile,
    [string]$CFlags,
    [string]$LdFlags
)

$ErrorActionPreference = "SilentlyContinue"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

function Find-Command($name) {
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

function Escape-String($s) {
    if (-not $s) { return "" }
    return $s -replace '([\\"])', '\$1'
}

####################
### Gather flex info
$LEX = if ($env:LEX) { $env:LEX } else { "flex" }
$LEX_PATH = Find-Command $LEX
if (-not $LEX_PATH) {
    # Try win_flex (from winflexbison package)
    $LEX_PATH = Find-Command "win_flex"
    if ($LEX_PATH) { $LEX = "win_flex" }
}

if (-not $LEX_PATH) {
    $LEX = "(missing)"
    $LEX_PATH = "(flex not found)"
    $LEX_VERSION = ""
} else {
    $LEX_VERSION = & $LEX --version 2>&1 | Select-Object -First 1
    if (-not $LEX_VERSION) { $LEX_VERSION = "" }
}
$LFLAGS = if ($env:LFLAGS) { $env:LFLAGS } else { "-Crema" }
$LFLAGS = Escape-String $LFLAGS

####################
### Gather bison info
$YACC = if ($env:YACC) { $env:YACC } elseif ($env:YACC -eq "bison -y") { "bison" } else { "bison" }
$YACC_PATH = Find-Command $YACC
if (-not $YACC_PATH) {
    # Try win_bison (from winflexbison package)
    $YACC_PATH = Find-Command "win_bison"
    if ($YACC_PATH) { $YACC = "win_bison" }
}

if (-not $YACC_PATH) {
    $YACC = "(missing)"
    $YACC_PATH = "(bison not found)"
    $YACC_VERSION = ""
    $YACC_PARSER_PREBUILT = Join-Path $ScriptDir "mdlparse.bison.c"
    if (Test-Path $YACC_PARSER_PREBUILT) {
        $firstLine = Get-Content $YACC_PARSER_PREBUILT -TotalCount 1
        if ($firstLine -match "GNU Bison (.+)\. ") {
            $YACC_VERSION = "not installed - using parser pregenerated by GNU Bison $($Matches[1])"
        } else {
            $YACC_VERSION = "not installed - using pregenerated parser"
        }
    } else {
        $YACC_VERSION = "not installed - build should fail"
    }
} else {
    $YACC_VERSION = & $YACC --version 2>&1 | Select-Object -First 1
    if (-not $YACC_VERSION) { $YACC_VERSION = "" }
}
$YFLAGS = if ($env:YFLAGS) { Escape-String $env:YFLAGS } else { "" }

####################
### Gather CC info
$CC = if ($env:CC) { $env:CC } else { "cl" }
$CC_PATH = Find-Command $CC
if ($CC_PATH) {
    if ($CC -eq "cl") {
        # MSVC cl.exe prints version info to stderr
        $CC_VERSION = & $CC 2>&1 | Select-Object -First 1
    } else {
        $CC_VERSION = & $CC --version 2>&1 | Select-Object -First 1
    }
} else {
    $CC_VERSION = ""
}
$CFLAGS = if ($env:CFLAGS) { Escape-String $env:CFLAGS } elseif ($CFlags) { Escape-String $CFlags } else { "" }

####################
### Gather LD info
$LD = if ($env:LD) { $env:LD } else { "link" }
$LD_PATH = Find-Command $LD
if ($LD_PATH) {
    if ($LD -eq "link") {
        # MSVC link.exe
        $LD_VERSION = & $LD 2>&1 | Select-Object -First 1
    } else {
        $LD_VERSION = & $LD --version 2>&1 | Select-Object -First 1
    }
} else {
    $LD_VERSION = ""
}
$LDFLAGS = if ($env:LDFLAGS) { Escape-String $env:LDFLAGS } elseif ($LdFlags) { Escape-String $LdFlags } else { "" }

####################
### Gather buildhost info
$BUILD_USER = $env:USERNAME
$BUILD_HOST = [System.Net.Dns]::GetHostEntry("").HostName
$SRC_DIR = (Resolve-Path $ScriptDir).Path
$BUILD_DIR = (Get-Location).Path
$BUILD_DATE = Get-Date -Format "ddd MMM dd HH:mm:ss yyyy"
$arch = if ([System.Environment]::Is64BitOperatingSystem) { "x86_64" } else { "x86" }
$BUILD_UNAME = "Windows $([System.Environment]::OSVersion.Version) $arch"

# Escape backslashes in Windows paths for C strings
$SRC_DIR = $SRC_DIR -replace '\\', '/'
$BUILD_DIR = $BUILD_DIR -replace '\\', '/'
$CC_PATH_ESC = if ($CC_PATH) { $CC_PATH -replace '\\', '/' } else { "" }
$LD_PATH_ESC = if ($LD_PATH) { $LD_PATH -replace '\\', '/' } else { "" }
$LEX_PATH_ESC = if ($LEX_PATH -and $LEX_PATH -ne "(flex not found)") { $LEX_PATH -replace '\\', '/' } else { $LEX_PATH }
$YACC_PATH_ESC = if ($YACC_PATH -and $YACC_PATH -ne "(bison not found)") { $YACC_PATH -replace '\\', '/' } else { $YACC_PATH }

####################
### Gather program version info
$version_path = Join-Path $ScriptDir "version.txt"
$MCELL_VERSION = (Get-Content $version_path -Raw).Trim()
$MCELL_HAVE_REVISION_INFO = 0

$GIT_PATH = Find-Command "git"
if ($GIT_PATH) {
    Push-Location $ScriptDir
    $gitCheck = & git describe --all --abbrev=4 HEAD 2>&1
    if ($LASTEXITCODE -eq 0) {
        $MCELL_HAVE_REVISION_INFO = 1
    }
    Pop-Location
}

####################
### Build the header content
if ($MCELL_HAVE_REVISION_INFO -eq 1) {
    Push-Location $ScriptDir
    $rev = & git show -s --format="%h"
    $revDate = & git show -s --format="%aD"
    $revBranch = & git rev-parse --abbrev-ref HEAD
    Pop-Location
}

$lines = @(
    "/****************************************************************"
    " * This file is automatically generated.  Do not edit it."
    " * version.h updated at ${BUILD_DATE} on ${BUILD_HOST} by ${BUILD_USER}"
    " ****************************************************************/"
    ""
    "/* Program version info */"
    "#define MCELL_VERSION `"${MCELL_VERSION}`""
)

if ($MCELL_HAVE_REVISION_INFO -eq 1) {
    $lines += "#define MCELL_REVISION `"${rev}`" "
    $lines += "#define MCELL_REVISION_DATE `"${revDate}`""
    $lines += "#define MCELL_REVISION_COMMITTED 1"
    $lines += "#define MCELL_REVISION_BRANCH `"${revBranch}`""
} else {
    $lines += "#define MCELL_REVISION `"`""
    $lines += "#define MCELL_REVISION_DATE `"`""
    $lines += "#define MCELL_REVISION_COMMITTED 0"
    $lines += "#define MCELL_REVISION_BRANCH `"not in VCS`""
}

$lines += @(
    ""
    "/* Build info */"
    "#define MCELL_BUILDDATE  `"${BUILD_DATE}`""
    "#define MCELL_BUILDUSER  `"${BUILD_USER}`""
    "#define MCELL_BUILDHOST  `"${BUILD_HOST}`""
    "#define MCELL_SRCDIR     `"${SRC_DIR}`""
    "#define MCELL_BUILDDIR   `"${BUILD_DIR}`""
    "#define MCELL_BUILDUNAME `"${BUILD_UNAME}`""
    ""
    "/* Tool identity and version info */"
    "#define MCELL_FLEX `"${LEX}`""
    "#define MCELL_FLEX_PATH `"${LEX_PATH_ESC}`""
    "#define MCELL_FLEX_VERSION `"${LEX_VERSION}`""
    "#define MCELL_FLEX_FLAGS `"${LFLAGS}`""
    "#define MCELL_BISON `"${YACC}`""
    "#define MCELL_BISON_PATH `"${YACC_PATH_ESC}`""
    "#define MCELL_BISON_VERSION `"${YACC_VERSION}`""
    "#define MCELL_BISON_FLAGS `"${YFLAGS}`""
    "#define MCELL_CC `"${CC}`""
    "#define MCELL_CC_PATH `"${CC_PATH_ESC}`""
    "#define MCELL_CC_VERSION `"${CC_VERSION}`""
    "#define MCELL_LD `"${LD}`""
    "#define MCELL_LD_PATH `"${LD_PATH_ESC}`""
    "#define MCELL_LD_VERSION `"${LD_VERSION}`""
    ""
    "/* Build options */"
    "#define MCELL_LFLAGS `"${LFLAGS}`""
    "#define MCELL_YFLAGS `"${YFLAGS}`""
    "#define MCELL_CFLAGS `"${CFLAGS}`""
    "#define MCELL_LDFLAGS `"${LDFLAGS}`""
)

####################
### Write output
if ($OutputFile) {
    $outDir = Split-Path -Parent $OutputFile
    if ($outDir -and -not (Test-Path $outDir)) {
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    }
    $lines | Out-File -FilePath $OutputFile -Encoding ascii
} else {
    $lines | Write-Output
}
